//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BrokerMessageEntities : DbContext
    {
        public BrokerMessageEntities()
            : base("name=BrokerMessageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spConsultaListaEmbarque_Result> spConsultaListaEmbarque()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaListaEmbarque_Result>("spConsultaListaEmbarque");
        }
    
        public virtual int spSalvaEmbarque(string iNStringSBLN, string iNStringSTDCOD, string iNStringDESCR, Nullable<System.DateTime> iNDateLASTUP, Nullable<int> iNIntIDDadosBroker)
        {
            var iNStringSBLNParameter = iNStringSBLN != null ?
                new ObjectParameter("INStringSBLN", iNStringSBLN) :
                new ObjectParameter("INStringSBLN", typeof(string));
    
            var iNStringSTDCODParameter = iNStringSTDCOD != null ?
                new ObjectParameter("INStringSTDCOD", iNStringSTDCOD) :
                new ObjectParameter("INStringSTDCOD", typeof(string));
    
            var iNStringDESCRParameter = iNStringDESCR != null ?
                new ObjectParameter("INStringDESCR", iNStringDESCR) :
                new ObjectParameter("INStringDESCR", typeof(string));
    
            var iNDateLASTUPParameter = iNDateLASTUP.HasValue ?
                new ObjectParameter("INDateLASTUP", iNDateLASTUP) :
                new ObjectParameter("INDateLASTUP", typeof(System.DateTime));
    
            var iNIntIDDadosBrokerParameter = iNIntIDDadosBroker.HasValue ?
                new ObjectParameter("INIntIDDadosBroker", iNIntIDDadosBroker) :
                new ObjectParameter("INIntIDDadosBroker", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSalvaEmbarque", iNStringSBLNParameter, iNStringSTDCODParameter, iNStringDESCRParameter, iNDateLASTUPParameter, iNIntIDDadosBrokerParameter);
        }
    
        public virtual ObjectResult<spConsultaEmbarque_Result> spConsultaEmbarque()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaEmbarque_Result>("spConsultaEmbarque");
        }
    
        public virtual int spSalvaSHPTEXT(Nullable<int> iNIntIDEmbarque, string inStringTDID, string inStringTDLINE, string iNStringTypeSHPTEX)
        {
            var iNIntIDEmbarqueParameter = iNIntIDEmbarque.HasValue ?
                new ObjectParameter("INIntIDEmbarque", iNIntIDEmbarque) :
                new ObjectParameter("INIntIDEmbarque", typeof(int));
    
            var inStringTDIDParameter = inStringTDID != null ?
                new ObjectParameter("InStringTDID", inStringTDID) :
                new ObjectParameter("InStringTDID", typeof(string));
    
            var inStringTDLINEParameter = inStringTDLINE != null ?
                new ObjectParameter("InStringTDLINE", inStringTDLINE) :
                new ObjectParameter("InStringTDLINE", typeof(string));
    
            var iNStringTypeSHPTEXParameter = iNStringTypeSHPTEX != null ?
                new ObjectParameter("INStringTypeSHPTEX", iNStringTypeSHPTEX) :
                new ObjectParameter("INStringTypeSHPTEX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSalvaSHPTEXT", iNIntIDEmbarqueParameter, inStringTDIDParameter, inStringTDLINEParameter, iNStringTypeSHPTEXParameter);
        }
    
        public virtual int spSalvaTGTEPRD(Nullable<int> iNIntIDEmbarque, string iNStringPARVW, string iNStringPARID, string iNStringNAME1, string iNStringNAME2, string iNStringSTREET, string iNStringHOUSE_NUM1, string iNStringHOUSE_NUM2, string iNStringPOST_CODE1, string iNStringCITY1, string iNStringCITY2, string iNStringPSTLZ, string iNStringREGION, string iNStringCOUNTRY, string iNStringSTCD1, string iNStringSTCD3, string iNStringSTCD4, string inStringTypeTGTEPRD)
        {
            var iNIntIDEmbarqueParameter = iNIntIDEmbarque.HasValue ?
                new ObjectParameter("INIntIDEmbarque", iNIntIDEmbarque) :
                new ObjectParameter("INIntIDEmbarque", typeof(int));
    
            var iNStringPARVWParameter = iNStringPARVW != null ?
                new ObjectParameter("INStringPARVW", iNStringPARVW) :
                new ObjectParameter("INStringPARVW", typeof(string));
    
            var iNStringPARIDParameter = iNStringPARID != null ?
                new ObjectParameter("INStringPARID", iNStringPARID) :
                new ObjectParameter("INStringPARID", typeof(string));
    
            var iNStringNAME1Parameter = iNStringNAME1 != null ?
                new ObjectParameter("INStringNAME1", iNStringNAME1) :
                new ObjectParameter("INStringNAME1", typeof(string));
    
            var iNStringNAME2Parameter = iNStringNAME2 != null ?
                new ObjectParameter("INStringNAME2", iNStringNAME2) :
                new ObjectParameter("INStringNAME2", typeof(string));
    
            var iNStringSTREETParameter = iNStringSTREET != null ?
                new ObjectParameter("INStringSTREET", iNStringSTREET) :
                new ObjectParameter("INStringSTREET", typeof(string));
    
            var iNStringHOUSE_NUM1Parameter = iNStringHOUSE_NUM1 != null ?
                new ObjectParameter("INStringHOUSE_NUM1", iNStringHOUSE_NUM1) :
                new ObjectParameter("INStringHOUSE_NUM1", typeof(string));
    
            var iNStringHOUSE_NUM2Parameter = iNStringHOUSE_NUM2 != null ?
                new ObjectParameter("INStringHOUSE_NUM2", iNStringHOUSE_NUM2) :
                new ObjectParameter("INStringHOUSE_NUM2", typeof(string));
    
            var iNStringPOST_CODE1Parameter = iNStringPOST_CODE1 != null ?
                new ObjectParameter("INStringPOST_CODE1", iNStringPOST_CODE1) :
                new ObjectParameter("INStringPOST_CODE1", typeof(string));
    
            var iNStringCITY1Parameter = iNStringCITY1 != null ?
                new ObjectParameter("INStringCITY1", iNStringCITY1) :
                new ObjectParameter("INStringCITY1", typeof(string));
    
            var iNStringCITY2Parameter = iNStringCITY2 != null ?
                new ObjectParameter("INStringCITY2", iNStringCITY2) :
                new ObjectParameter("INStringCITY2", typeof(string));
    
            var iNStringPSTLZParameter = iNStringPSTLZ != null ?
                new ObjectParameter("INStringPSTLZ", iNStringPSTLZ) :
                new ObjectParameter("INStringPSTLZ", typeof(string));
    
            var iNStringREGIONParameter = iNStringREGION != null ?
                new ObjectParameter("INStringREGION", iNStringREGION) :
                new ObjectParameter("INStringREGION", typeof(string));
    
            var iNStringCOUNTRYParameter = iNStringCOUNTRY != null ?
                new ObjectParameter("INStringCOUNTRY", iNStringCOUNTRY) :
                new ObjectParameter("INStringCOUNTRY", typeof(string));
    
            var iNStringSTCD1Parameter = iNStringSTCD1 != null ?
                new ObjectParameter("INStringSTCD1", iNStringSTCD1) :
                new ObjectParameter("INStringSTCD1", typeof(string));
    
            var iNStringSTCD3Parameter = iNStringSTCD3 != null ?
                new ObjectParameter("INStringSTCD3", iNStringSTCD3) :
                new ObjectParameter("INStringSTCD3", typeof(string));
    
            var iNStringSTCD4Parameter = iNStringSTCD4 != null ?
                new ObjectParameter("INStringSTCD4", iNStringSTCD4) :
                new ObjectParameter("INStringSTCD4", typeof(string));
    
            var inStringTypeTGTEPRDParameter = inStringTypeTGTEPRD != null ?
                new ObjectParameter("InStringTypeTGTEPRD", inStringTypeTGTEPRD) :
                new ObjectParameter("InStringTypeTGTEPRD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSalvaTGTEPRD", iNIntIDEmbarqueParameter, iNStringPARVWParameter, iNStringPARIDParameter, iNStringNAME1Parameter, iNStringNAME2Parameter, iNStringSTREETParameter, iNStringHOUSE_NUM1Parameter, iNStringHOUSE_NUM2Parameter, iNStringPOST_CODE1Parameter, iNStringCITY1Parameter, iNStringCITY2Parameter, iNStringPSTLZParameter, iNStringREGIONParameter, iNStringCOUNTRYParameter, iNStringSTCD1Parameter, iNStringSTCD3Parameter, iNStringSTCD4Parameter, inStringTypeTGTEPRDParameter);
        }
    
        public virtual int spSalvaTGTERES(Nullable<int> iNIntIDEmbarque, string iNStringDSENUM, string iNStringRENUM, Nullable<System.DateTime> iNDateANDAT, Nullable<System.DateTime> iNDateREDAT, Nullable<System.DateTime> iNDateAVBDT, string iNCharCANAL, string iNStringDDENUM, Nullable<System.DateTime> iNDateDDEDT, string iNStringDDESQ, string iNStringREANX, Nullable<int> iNIntDSESQ, string iNStringDOCFAT, string iNStringXBLNR, string iNStringINCO1, string iNStringWAERS, Nullable<System.DateTime> iNDateDDEADT, string iNStringTypeTGTERES)
        {
            var iNIntIDEmbarqueParameter = iNIntIDEmbarque.HasValue ?
                new ObjectParameter("INIntIDEmbarque", iNIntIDEmbarque) :
                new ObjectParameter("INIntIDEmbarque", typeof(int));
    
            var iNStringDSENUMParameter = iNStringDSENUM != null ?
                new ObjectParameter("INStringDSENUM", iNStringDSENUM) :
                new ObjectParameter("INStringDSENUM", typeof(string));
    
            var iNStringRENUMParameter = iNStringRENUM != null ?
                new ObjectParameter("INStringRENUM", iNStringRENUM) :
                new ObjectParameter("INStringRENUM", typeof(string));
    
            var iNDateANDATParameter = iNDateANDAT.HasValue ?
                new ObjectParameter("INDateANDAT", iNDateANDAT) :
                new ObjectParameter("INDateANDAT", typeof(System.DateTime));
    
            var iNDateREDATParameter = iNDateREDAT.HasValue ?
                new ObjectParameter("INDateREDAT", iNDateREDAT) :
                new ObjectParameter("INDateREDAT", typeof(System.DateTime));
    
            var iNDateAVBDTParameter = iNDateAVBDT.HasValue ?
                new ObjectParameter("INDateAVBDT", iNDateAVBDT) :
                new ObjectParameter("INDateAVBDT", typeof(System.DateTime));
    
            var iNCharCANALParameter = iNCharCANAL != null ?
                new ObjectParameter("INCharCANAL", iNCharCANAL) :
                new ObjectParameter("INCharCANAL", typeof(string));
    
            var iNStringDDENUMParameter = iNStringDDENUM != null ?
                new ObjectParameter("INStringDDENUM", iNStringDDENUM) :
                new ObjectParameter("INStringDDENUM", typeof(string));
    
            var iNDateDDEDTParameter = iNDateDDEDT.HasValue ?
                new ObjectParameter("INDateDDEDT", iNDateDDEDT) :
                new ObjectParameter("INDateDDEDT", typeof(System.DateTime));
    
            var iNStringDDESQParameter = iNStringDDESQ != null ?
                new ObjectParameter("INStringDDESQ", iNStringDDESQ) :
                new ObjectParameter("INStringDDESQ", typeof(string));
    
            var iNStringREANXParameter = iNStringREANX != null ?
                new ObjectParameter("INStringREANX", iNStringREANX) :
                new ObjectParameter("INStringREANX", typeof(string));
    
            var iNIntDSESQParameter = iNIntDSESQ.HasValue ?
                new ObjectParameter("INIntDSESQ", iNIntDSESQ) :
                new ObjectParameter("INIntDSESQ", typeof(int));
    
            var iNStringDOCFATParameter = iNStringDOCFAT != null ?
                new ObjectParameter("INStringDOCFAT", iNStringDOCFAT) :
                new ObjectParameter("INStringDOCFAT", typeof(string));
    
            var iNStringXBLNRParameter = iNStringXBLNR != null ?
                new ObjectParameter("INStringXBLNR", iNStringXBLNR) :
                new ObjectParameter("INStringXBLNR", typeof(string));
    
            var iNStringINCO1Parameter = iNStringINCO1 != null ?
                new ObjectParameter("INStringINCO1", iNStringINCO1) :
                new ObjectParameter("INStringINCO1", typeof(string));
    
            var iNStringWAERSParameter = iNStringWAERS != null ?
                new ObjectParameter("INStringWAERS", iNStringWAERS) :
                new ObjectParameter("INStringWAERS", typeof(string));
    
            var iNDateDDEADTParameter = iNDateDDEADT.HasValue ?
                new ObjectParameter("INDateDDEADT", iNDateDDEADT) :
                new ObjectParameter("INDateDDEADT", typeof(System.DateTime));
    
            var iNStringTypeTGTERESParameter = iNStringTypeTGTERES != null ?
                new ObjectParameter("INStringTypeTGTERES", iNStringTypeTGTERES) :
                new ObjectParameter("INStringTypeTGTERES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSalvaTGTERES", iNIntIDEmbarqueParameter, iNStringDSENUMParameter, iNStringRENUMParameter, iNDateANDATParameter, iNDateREDATParameter, iNDateAVBDTParameter, iNCharCANALParameter, iNStringDDENUMParameter, iNDateDDEDTParameter, iNStringDDESQParameter, iNStringREANXParameter, iNIntDSESQParameter, iNStringDOCFATParameter, iNStringXBLNRParameter, iNStringINCO1Parameter, iNStringWAERSParameter, iNDateDDEADTParameter, iNStringTypeTGTERESParameter);
        }
    
        public virtual int spSalvaTGTESHKN(Nullable<int> iNIntIDEmbarque, string iNCharLOCSE, string iNCharTIPSE, string iNCharTSETMP, Nullable<System.DateTime> iNDateSEDAT, Nullable<System.DateTime> iNDateETADT, Nullable<System.DateTime> iNDateENVDT, Nullable<System.DateTime> iNDatePREVDT, string iNStringTRANS, string iNStringZOLLAO, string iNStringZLANDO, string iNStringZOLLAD, string iNStringZLANDD, Nullable<decimal> iNDecimal_15_3_NETWR, string iNStringWAERSRF, string iNStringINCO1, string iNStringZTERM, string iNStringSESTAT, string iNStringWAERS, string iNStringBFMAR, string iNStringSHPTRIP, Nullable<System.DateTime> iNDateETDDT, string iNStringBLNMB, Nullable<System.DateTime> iNDateBLDTA, string iNStringHSAWB, string iNStringSHPNAM, string iNStringINVNR, Nullable<System.DateTime> iNDateDT_INVNR, Nullable<decimal> iNDecimal_13_3_VOLUM, Nullable<decimal> iNDecimal_13_3_NTGEW, Nullable<decimal> iNDecimal_13_3_BRGEW, Nullable<decimal> iNDecimal_15_3_VLFRETE, string iNStringMOEDAFRT, Nullable<decimal> iNDecimal_15_3_VLSEGURO, string iNStringMOEDASGR, Nullable<decimal> iNDecimal_15_3_VLCOAGT, string iNStringMOEDACOAGT, Nullable<decimal> iNDecimal_5_3_PCCOAGT, string iNStringTPCOAGT, Nullable<System.DateTime> iNDateDTCLTC, Nullable<System.DateTime> iNDateDTEARM, Nullable<System.DateTime> iNDateDTENTC, string iNStringURFDESP, string iNStringURFEMBA, string iNCharMODPAG, string iNCharBASCOM, string iNCharPRECLCT, Nullable<System.DateTime> iNDateDTCOLETA, Nullable<System.DateTime> iNDateDTCHGARM, Nullable<System.DateTime> iNDateDTPRESC, Nullable<System.DateTime> iNDateDTAVERB, Nullable<System.DateTime> iNDateDTENTREGA, string iNStringBROKNM, string iNStringNMBOOK, Nullable<System.DateTime> iNDateDTBOOK, string iNStringTPVEIC, string iNStringTPCARG, string iNStringUFEMBARQ, string iNStringINSTNEG, string iNStringTPPRP, Nullable<System.DateTime> iNDateDTSHIP, string iNStringNROCE, Nullable<System.DateTime> iNDateDTCE, string iNStringTypeTGTESHKN)
        {
            var iNIntIDEmbarqueParameter = iNIntIDEmbarque.HasValue ?
                new ObjectParameter("INIntIDEmbarque", iNIntIDEmbarque) :
                new ObjectParameter("INIntIDEmbarque", typeof(int));
    
            var iNCharLOCSEParameter = iNCharLOCSE != null ?
                new ObjectParameter("INCharLOCSE", iNCharLOCSE) :
                new ObjectParameter("INCharLOCSE", typeof(string));
    
            var iNCharTIPSEParameter = iNCharTIPSE != null ?
                new ObjectParameter("INCharTIPSE", iNCharTIPSE) :
                new ObjectParameter("INCharTIPSE", typeof(string));
    
            var iNCharTSETMPParameter = iNCharTSETMP != null ?
                new ObjectParameter("INCharTSETMP", iNCharTSETMP) :
                new ObjectParameter("INCharTSETMP", typeof(string));
    
            var iNDateSEDATParameter = iNDateSEDAT.HasValue ?
                new ObjectParameter("INDateSEDAT", iNDateSEDAT) :
                new ObjectParameter("INDateSEDAT", typeof(System.DateTime));
    
            var iNDateETADTParameter = iNDateETADT.HasValue ?
                new ObjectParameter("INDateETADT", iNDateETADT) :
                new ObjectParameter("INDateETADT", typeof(System.DateTime));
    
            var iNDateENVDTParameter = iNDateENVDT.HasValue ?
                new ObjectParameter("INDateENVDT", iNDateENVDT) :
                new ObjectParameter("INDateENVDT", typeof(System.DateTime));
    
            var iNDatePREVDTParameter = iNDatePREVDT.HasValue ?
                new ObjectParameter("INDatePREVDT", iNDatePREVDT) :
                new ObjectParameter("INDatePREVDT", typeof(System.DateTime));
    
            var iNStringTRANSParameter = iNStringTRANS != null ?
                new ObjectParameter("INStringTRANS", iNStringTRANS) :
                new ObjectParameter("INStringTRANS", typeof(string));
    
            var iNStringZOLLAOParameter = iNStringZOLLAO != null ?
                new ObjectParameter("INStringZOLLAO", iNStringZOLLAO) :
                new ObjectParameter("INStringZOLLAO", typeof(string));
    
            var iNStringZLANDOParameter = iNStringZLANDO != null ?
                new ObjectParameter("INStringZLANDO", iNStringZLANDO) :
                new ObjectParameter("INStringZLANDO", typeof(string));
    
            var iNStringZOLLADParameter = iNStringZOLLAD != null ?
                new ObjectParameter("INStringZOLLAD", iNStringZOLLAD) :
                new ObjectParameter("INStringZOLLAD", typeof(string));
    
            var iNStringZLANDDParameter = iNStringZLANDD != null ?
                new ObjectParameter("INStringZLANDD", iNStringZLANDD) :
                new ObjectParameter("INStringZLANDD", typeof(string));
    
            var iNDecimal_15_3_NETWRParameter = iNDecimal_15_3_NETWR.HasValue ?
                new ObjectParameter("INDecimal_15_3_NETWR", iNDecimal_15_3_NETWR) :
                new ObjectParameter("INDecimal_15_3_NETWR", typeof(decimal));
    
            var iNStringWAERSRFParameter = iNStringWAERSRF != null ?
                new ObjectParameter("INStringWAERSRF", iNStringWAERSRF) :
                new ObjectParameter("INStringWAERSRF", typeof(string));
    
            var iNStringINCO1Parameter = iNStringINCO1 != null ?
                new ObjectParameter("INStringINCO1", iNStringINCO1) :
                new ObjectParameter("INStringINCO1", typeof(string));
    
            var iNStringZTERMParameter = iNStringZTERM != null ?
                new ObjectParameter("INStringZTERM", iNStringZTERM) :
                new ObjectParameter("INStringZTERM", typeof(string));
    
            var iNStringSESTATParameter = iNStringSESTAT != null ?
                new ObjectParameter("INStringSESTAT", iNStringSESTAT) :
                new ObjectParameter("INStringSESTAT", typeof(string));
    
            var iNStringWAERSParameter = iNStringWAERS != null ?
                new ObjectParameter("INStringWAERS", iNStringWAERS) :
                new ObjectParameter("INStringWAERS", typeof(string));
    
            var iNStringBFMARParameter = iNStringBFMAR != null ?
                new ObjectParameter("INStringBFMAR", iNStringBFMAR) :
                new ObjectParameter("INStringBFMAR", typeof(string));
    
            var iNStringSHPTRIPParameter = iNStringSHPTRIP != null ?
                new ObjectParameter("INStringSHPTRIP", iNStringSHPTRIP) :
                new ObjectParameter("INStringSHPTRIP", typeof(string));
    
            var iNDateETDDTParameter = iNDateETDDT.HasValue ?
                new ObjectParameter("INDateETDDT", iNDateETDDT) :
                new ObjectParameter("INDateETDDT", typeof(System.DateTime));
    
            var iNStringBLNMBParameter = iNStringBLNMB != null ?
                new ObjectParameter("INStringBLNMB", iNStringBLNMB) :
                new ObjectParameter("INStringBLNMB", typeof(string));
    
            var iNDateBLDTAParameter = iNDateBLDTA.HasValue ?
                new ObjectParameter("INDateBLDTA", iNDateBLDTA) :
                new ObjectParameter("INDateBLDTA", typeof(System.DateTime));
    
            var iNStringHSAWBParameter = iNStringHSAWB != null ?
                new ObjectParameter("INStringHSAWB", iNStringHSAWB) :
                new ObjectParameter("INStringHSAWB", typeof(string));
    
            var iNStringSHPNAMParameter = iNStringSHPNAM != null ?
                new ObjectParameter("INStringSHPNAM", iNStringSHPNAM) :
                new ObjectParameter("INStringSHPNAM", typeof(string));
    
            var iNStringINVNRParameter = iNStringINVNR != null ?
                new ObjectParameter("INStringINVNR", iNStringINVNR) :
                new ObjectParameter("INStringINVNR", typeof(string));
    
            var iNDateDT_INVNRParameter = iNDateDT_INVNR.HasValue ?
                new ObjectParameter("INDateDT_INVNR", iNDateDT_INVNR) :
                new ObjectParameter("INDateDT_INVNR", typeof(System.DateTime));
    
            var iNDecimal_13_3_VOLUMParameter = iNDecimal_13_3_VOLUM.HasValue ?
                new ObjectParameter("INDecimal_13_3_VOLUM", iNDecimal_13_3_VOLUM) :
                new ObjectParameter("INDecimal_13_3_VOLUM", typeof(decimal));
    
            var iNDecimal_13_3_NTGEWParameter = iNDecimal_13_3_NTGEW.HasValue ?
                new ObjectParameter("INDecimal_13_3_NTGEW", iNDecimal_13_3_NTGEW) :
                new ObjectParameter("INDecimal_13_3_NTGEW", typeof(decimal));
    
            var iNDecimal_13_3_BRGEWParameter = iNDecimal_13_3_BRGEW.HasValue ?
                new ObjectParameter("INDecimal_13_3_BRGEW", iNDecimal_13_3_BRGEW) :
                new ObjectParameter("INDecimal_13_3_BRGEW", typeof(decimal));
    
            var iNDecimal_15_3_VLFRETEParameter = iNDecimal_15_3_VLFRETE.HasValue ?
                new ObjectParameter("INDecimal_15_3_VLFRETE", iNDecimal_15_3_VLFRETE) :
                new ObjectParameter("INDecimal_15_3_VLFRETE", typeof(decimal));
    
            var iNStringMOEDAFRTParameter = iNStringMOEDAFRT != null ?
                new ObjectParameter("INStringMOEDAFRT", iNStringMOEDAFRT) :
                new ObjectParameter("INStringMOEDAFRT", typeof(string));
    
            var iNDecimal_15_3_VLSEGUROParameter = iNDecimal_15_3_VLSEGURO.HasValue ?
                new ObjectParameter("INDecimal_15_3_VLSEGURO", iNDecimal_15_3_VLSEGURO) :
                new ObjectParameter("INDecimal_15_3_VLSEGURO", typeof(decimal));
    
            var iNStringMOEDASGRParameter = iNStringMOEDASGR != null ?
                new ObjectParameter("INStringMOEDASGR", iNStringMOEDASGR) :
                new ObjectParameter("INStringMOEDASGR", typeof(string));
    
            var iNDecimal_15_3_VLCOAGTParameter = iNDecimal_15_3_VLCOAGT.HasValue ?
                new ObjectParameter("INDecimal_15_3_VLCOAGT", iNDecimal_15_3_VLCOAGT) :
                new ObjectParameter("INDecimal_15_3_VLCOAGT", typeof(decimal));
    
            var iNStringMOEDACOAGTParameter = iNStringMOEDACOAGT != null ?
                new ObjectParameter("INStringMOEDACOAGT", iNStringMOEDACOAGT) :
                new ObjectParameter("INStringMOEDACOAGT", typeof(string));
    
            var iNDecimal_5_3_PCCOAGTParameter = iNDecimal_5_3_PCCOAGT.HasValue ?
                new ObjectParameter("INDecimal_5_3_PCCOAGT", iNDecimal_5_3_PCCOAGT) :
                new ObjectParameter("INDecimal_5_3_PCCOAGT", typeof(decimal));
    
            var iNStringTPCOAGTParameter = iNStringTPCOAGT != null ?
                new ObjectParameter("INStringTPCOAGT", iNStringTPCOAGT) :
                new ObjectParameter("INStringTPCOAGT", typeof(string));
    
            var iNDateDTCLTCParameter = iNDateDTCLTC.HasValue ?
                new ObjectParameter("INDateDTCLTC", iNDateDTCLTC) :
                new ObjectParameter("INDateDTCLTC", typeof(System.DateTime));
    
            var iNDateDTEARMParameter = iNDateDTEARM.HasValue ?
                new ObjectParameter("INDateDTEARM", iNDateDTEARM) :
                new ObjectParameter("INDateDTEARM", typeof(System.DateTime));
    
            var iNDateDTENTCParameter = iNDateDTENTC.HasValue ?
                new ObjectParameter("INDateDTENTC", iNDateDTENTC) :
                new ObjectParameter("INDateDTENTC", typeof(System.DateTime));
    
            var iNStringURFDESPParameter = iNStringURFDESP != null ?
                new ObjectParameter("INStringURFDESP", iNStringURFDESP) :
                new ObjectParameter("INStringURFDESP", typeof(string));
    
            var iNStringURFEMBAParameter = iNStringURFEMBA != null ?
                new ObjectParameter("INStringURFEMBA", iNStringURFEMBA) :
                new ObjectParameter("INStringURFEMBA", typeof(string));
    
            var iNCharMODPAGParameter = iNCharMODPAG != null ?
                new ObjectParameter("INCharMODPAG", iNCharMODPAG) :
                new ObjectParameter("INCharMODPAG", typeof(string));
    
            var iNCharBASCOMParameter = iNCharBASCOM != null ?
                new ObjectParameter("INCharBASCOM", iNCharBASCOM) :
                new ObjectParameter("INCharBASCOM", typeof(string));
    
            var iNCharPRECLCTParameter = iNCharPRECLCT != null ?
                new ObjectParameter("INCharPRECLCT", iNCharPRECLCT) :
                new ObjectParameter("INCharPRECLCT", typeof(string));
    
            var iNDateDTCOLETAParameter = iNDateDTCOLETA.HasValue ?
                new ObjectParameter("INDateDTCOLETA", iNDateDTCOLETA) :
                new ObjectParameter("INDateDTCOLETA", typeof(System.DateTime));
    
            var iNDateDTCHGARMParameter = iNDateDTCHGARM.HasValue ?
                new ObjectParameter("INDateDTCHGARM", iNDateDTCHGARM) :
                new ObjectParameter("INDateDTCHGARM", typeof(System.DateTime));
    
            var iNDateDTPRESCParameter = iNDateDTPRESC.HasValue ?
                new ObjectParameter("INDateDTPRESC", iNDateDTPRESC) :
                new ObjectParameter("INDateDTPRESC", typeof(System.DateTime));
    
            var iNDateDTAVERBParameter = iNDateDTAVERB.HasValue ?
                new ObjectParameter("INDateDTAVERB", iNDateDTAVERB) :
                new ObjectParameter("INDateDTAVERB", typeof(System.DateTime));
    
            var iNDateDTENTREGAParameter = iNDateDTENTREGA.HasValue ?
                new ObjectParameter("INDateDTENTREGA", iNDateDTENTREGA) :
                new ObjectParameter("INDateDTENTREGA", typeof(System.DateTime));
    
            var iNStringBROKNMParameter = iNStringBROKNM != null ?
                new ObjectParameter("INStringBROKNM", iNStringBROKNM) :
                new ObjectParameter("INStringBROKNM", typeof(string));
    
            var iNStringNMBOOKParameter = iNStringNMBOOK != null ?
                new ObjectParameter("INStringNMBOOK", iNStringNMBOOK) :
                new ObjectParameter("INStringNMBOOK", typeof(string));
    
            var iNDateDTBOOKParameter = iNDateDTBOOK.HasValue ?
                new ObjectParameter("INDateDTBOOK", iNDateDTBOOK) :
                new ObjectParameter("INDateDTBOOK", typeof(System.DateTime));
    
            var iNStringTPVEICParameter = iNStringTPVEIC != null ?
                new ObjectParameter("INStringTPVEIC", iNStringTPVEIC) :
                new ObjectParameter("INStringTPVEIC", typeof(string));
    
            var iNStringTPCARGParameter = iNStringTPCARG != null ?
                new ObjectParameter("INStringTPCARG", iNStringTPCARG) :
                new ObjectParameter("INStringTPCARG", typeof(string));
    
            var iNStringUFEMBARQParameter = iNStringUFEMBARQ != null ?
                new ObjectParameter("INStringUFEMBARQ", iNStringUFEMBARQ) :
                new ObjectParameter("INStringUFEMBARQ", typeof(string));
    
            var iNStringINSTNEGParameter = iNStringINSTNEG != null ?
                new ObjectParameter("INStringINSTNEG", iNStringINSTNEG) :
                new ObjectParameter("INStringINSTNEG", typeof(string));
    
            var iNStringTPPRPParameter = iNStringTPPRP != null ?
                new ObjectParameter("INStringTPPRP", iNStringTPPRP) :
                new ObjectParameter("INStringTPPRP", typeof(string));
    
            var iNDateDTSHIPParameter = iNDateDTSHIP.HasValue ?
                new ObjectParameter("INDateDTSHIP", iNDateDTSHIP) :
                new ObjectParameter("INDateDTSHIP", typeof(System.DateTime));
    
            var iNStringNROCEParameter = iNStringNROCE != null ?
                new ObjectParameter("INStringNROCE", iNStringNROCE) :
                new ObjectParameter("INStringNROCE", typeof(string));
    
            var iNDateDTCEParameter = iNDateDTCE.HasValue ?
                new ObjectParameter("INDateDTCE", iNDateDTCE) :
                new ObjectParameter("INDateDTCE", typeof(System.DateTime));
    
            var iNStringTypeTGTESHKNParameter = iNStringTypeTGTESHKN != null ?
                new ObjectParameter("INStringTypeTGTESHKN", iNStringTypeTGTESHKN) :
                new ObjectParameter("INStringTypeTGTESHKN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSalvaTGTESHKN", iNIntIDEmbarqueParameter, iNCharLOCSEParameter, iNCharTIPSEParameter, iNCharTSETMPParameter, iNDateSEDATParameter, iNDateETADTParameter, iNDateENVDTParameter, iNDatePREVDTParameter, iNStringTRANSParameter, iNStringZOLLAOParameter, iNStringZLANDOParameter, iNStringZOLLADParameter, iNStringZLANDDParameter, iNDecimal_15_3_NETWRParameter, iNStringWAERSRFParameter, iNStringINCO1Parameter, iNStringZTERMParameter, iNStringSESTATParameter, iNStringWAERSParameter, iNStringBFMARParameter, iNStringSHPTRIPParameter, iNDateETDDTParameter, iNStringBLNMBParameter, iNDateBLDTAParameter, iNStringHSAWBParameter, iNStringSHPNAMParameter, iNStringINVNRParameter, iNDateDT_INVNRParameter, iNDecimal_13_3_VOLUMParameter, iNDecimal_13_3_NTGEWParameter, iNDecimal_13_3_BRGEWParameter, iNDecimal_15_3_VLFRETEParameter, iNStringMOEDAFRTParameter, iNDecimal_15_3_VLSEGUROParameter, iNStringMOEDASGRParameter, iNDecimal_15_3_VLCOAGTParameter, iNStringMOEDACOAGTParameter, iNDecimal_5_3_PCCOAGTParameter, iNStringTPCOAGTParameter, iNDateDTCLTCParameter, iNDateDTEARMParameter, iNDateDTENTCParameter, iNStringURFDESPParameter, iNStringURFEMBAParameter, iNCharMODPAGParameter, iNCharBASCOMParameter, iNCharPRECLCTParameter, iNDateDTCOLETAParameter, iNDateDTCHGARMParameter, iNDateDTPRESCParameter, iNDateDTAVERBParameter, iNDateDTENTREGAParameter, iNStringBROKNMParameter, iNStringNMBOOKParameter, iNDateDTBOOKParameter, iNStringTPVEICParameter, iNStringTPCARGParameter, iNStringUFEMBARQParameter, iNStringINSTNEGParameter, iNStringTPPRPParameter, iNDateDTSHIPParameter, iNStringNROCEParameter, iNDateDTCEParameter, iNStringTypeTGTESHKNParameter);
        }
    
        public virtual int spSalvaTGTESHPN(Nullable<int> iNIntIDEmbarque, Nullable<int> iNIntSBELP, Nullable<int> iNIntNBELP, string iNStringDOCFAT, Nullable<decimal> iNNumeric_13_3_ITMFAT, string iNStringMATNR, string iNStringMAKTX, Nullable<decimal> iNNumeric_11_2_QTDITM, Nullable<decimal> iNDecimal_11_2_NETPR, Nullable<decimal> iNDecimal_5_0_KPEIN, string iNStringMEINS, Nullable<decimal> iNDecimal_11_2_NETWR, Nullable<decimal> iNDecimal_15_2_FRTLOC, Nullable<decimal> iNDecimal_15_2_FRTINT, Nullable<decimal> iNDecimal_15_2_SEGINT, Nullable<decimal> iNDecimal_15_2_PRCFOB, Nullable<decimal> iNDecimal_15_2_PRCEXW, Nullable<decimal> iNDecimal_15_2_PCTCOM, Nullable<decimal> iNDecimal_15_2_VLRCOM, string iNStringRENUM, Nullable<int> iNIntITMRE, string iNStringENQDM, Nullable<decimal> iNNumeric_13_3_BRGEW, Nullable<decimal> iNNumeric_13_3_NTGEW, string iNStringGEWEI, Nullable<decimal> iNNumeric_13_3_VOLUM, string iNStringVOLEH, string iNStringSTEUC, string iNStringNALADISH, string iNStringFABITM, string iNStringATOCON, string iNCharAMCCPTC, string iNCharBRCCPTC, string iNCharCCROM, string iNStringFABRILUF, Nullable<decimal> iNDecimal_11_2_NETPRORI, Nullable<decimal> iNDecimal_5_0_KPEINORI, string iNStringMEINSORI, Nullable<decimal> iNDecimal_15_2_NETWRORI, string iNStringPROD, Nullable<System.DateTime> iNDateFKDAT, string iNStringTypeTGTESHPN, ObjectParameter oUTId)
        {
            var iNIntIDEmbarqueParameter = iNIntIDEmbarque.HasValue ?
                new ObjectParameter("INIntIDEmbarque", iNIntIDEmbarque) :
                new ObjectParameter("INIntIDEmbarque", typeof(int));
    
            var iNIntSBELPParameter = iNIntSBELP.HasValue ?
                new ObjectParameter("INIntSBELP", iNIntSBELP) :
                new ObjectParameter("INIntSBELP", typeof(int));
    
            var iNIntNBELPParameter = iNIntNBELP.HasValue ?
                new ObjectParameter("INIntNBELP", iNIntNBELP) :
                new ObjectParameter("INIntNBELP", typeof(int));
    
            var iNStringDOCFATParameter = iNStringDOCFAT != null ?
                new ObjectParameter("INStringDOCFAT", iNStringDOCFAT) :
                new ObjectParameter("INStringDOCFAT", typeof(string));
    
            var iNNumeric_13_3_ITMFATParameter = iNNumeric_13_3_ITMFAT.HasValue ?
                new ObjectParameter("INNumeric_13_3_ITMFAT", iNNumeric_13_3_ITMFAT) :
                new ObjectParameter("INNumeric_13_3_ITMFAT", typeof(decimal));
    
            var iNStringMATNRParameter = iNStringMATNR != null ?
                new ObjectParameter("INStringMATNR", iNStringMATNR) :
                new ObjectParameter("INStringMATNR", typeof(string));
    
            var iNStringMAKTXParameter = iNStringMAKTX != null ?
                new ObjectParameter("INStringMAKTX", iNStringMAKTX) :
                new ObjectParameter("INStringMAKTX", typeof(string));
    
            var iNNumeric_11_2_QTDITMParameter = iNNumeric_11_2_QTDITM.HasValue ?
                new ObjectParameter("INNumeric_11_2_QTDITM", iNNumeric_11_2_QTDITM) :
                new ObjectParameter("INNumeric_11_2_QTDITM", typeof(decimal));
    
            var iNDecimal_11_2_NETPRParameter = iNDecimal_11_2_NETPR.HasValue ?
                new ObjectParameter("INDecimal_11_2_NETPR", iNDecimal_11_2_NETPR) :
                new ObjectParameter("INDecimal_11_2_NETPR", typeof(decimal));
    
            var iNDecimal_5_0_KPEINParameter = iNDecimal_5_0_KPEIN.HasValue ?
                new ObjectParameter("INDecimal_5_0_KPEIN", iNDecimal_5_0_KPEIN) :
                new ObjectParameter("INDecimal_5_0_KPEIN", typeof(decimal));
    
            var iNStringMEINSParameter = iNStringMEINS != null ?
                new ObjectParameter("INStringMEINS", iNStringMEINS) :
                new ObjectParameter("INStringMEINS", typeof(string));
    
            var iNDecimal_11_2_NETWRParameter = iNDecimal_11_2_NETWR.HasValue ?
                new ObjectParameter("INDecimal_11_2_NETWR", iNDecimal_11_2_NETWR) :
                new ObjectParameter("INDecimal_11_2_NETWR", typeof(decimal));
    
            var iNDecimal_15_2_FRTLOCParameter = iNDecimal_15_2_FRTLOC.HasValue ?
                new ObjectParameter("INDecimal_15_2_FRTLOC", iNDecimal_15_2_FRTLOC) :
                new ObjectParameter("INDecimal_15_2_FRTLOC", typeof(decimal));
    
            var iNDecimal_15_2_FRTINTParameter = iNDecimal_15_2_FRTINT.HasValue ?
                new ObjectParameter("INDecimal_15_2_FRTINT", iNDecimal_15_2_FRTINT) :
                new ObjectParameter("INDecimal_15_2_FRTINT", typeof(decimal));
    
            var iNDecimal_15_2_SEGINTParameter = iNDecimal_15_2_SEGINT.HasValue ?
                new ObjectParameter("INDecimal_15_2_SEGINT", iNDecimal_15_2_SEGINT) :
                new ObjectParameter("INDecimal_15_2_SEGINT", typeof(decimal));
    
            var iNDecimal_15_2_PRCFOBParameter = iNDecimal_15_2_PRCFOB.HasValue ?
                new ObjectParameter("INDecimal_15_2_PRCFOB", iNDecimal_15_2_PRCFOB) :
                new ObjectParameter("INDecimal_15_2_PRCFOB", typeof(decimal));
    
            var iNDecimal_15_2_PRCEXWParameter = iNDecimal_15_2_PRCEXW.HasValue ?
                new ObjectParameter("INDecimal_15_2_PRCEXW", iNDecimal_15_2_PRCEXW) :
                new ObjectParameter("INDecimal_15_2_PRCEXW", typeof(decimal));
    
            var iNDecimal_15_2_PCTCOMParameter = iNDecimal_15_2_PCTCOM.HasValue ?
                new ObjectParameter("INDecimal_15_2_PCTCOM", iNDecimal_15_2_PCTCOM) :
                new ObjectParameter("INDecimal_15_2_PCTCOM", typeof(decimal));
    
            var iNDecimal_15_2_VLRCOMParameter = iNDecimal_15_2_VLRCOM.HasValue ?
                new ObjectParameter("INDecimal_15_2_VLRCOM", iNDecimal_15_2_VLRCOM) :
                new ObjectParameter("INDecimal_15_2_VLRCOM", typeof(decimal));
    
            var iNStringRENUMParameter = iNStringRENUM != null ?
                new ObjectParameter("INStringRENUM", iNStringRENUM) :
                new ObjectParameter("INStringRENUM", typeof(string));
    
            var iNIntITMREParameter = iNIntITMRE.HasValue ?
                new ObjectParameter("INIntITMRE", iNIntITMRE) :
                new ObjectParameter("INIntITMRE", typeof(int));
    
            var iNStringENQDMParameter = iNStringENQDM != null ?
                new ObjectParameter("INStringENQDM", iNStringENQDM) :
                new ObjectParameter("INStringENQDM", typeof(string));
    
            var iNNumeric_13_3_BRGEWParameter = iNNumeric_13_3_BRGEW.HasValue ?
                new ObjectParameter("INNumeric_13_3_BRGEW", iNNumeric_13_3_BRGEW) :
                new ObjectParameter("INNumeric_13_3_BRGEW", typeof(decimal));
    
            var iNNumeric_13_3_NTGEWParameter = iNNumeric_13_3_NTGEW.HasValue ?
                new ObjectParameter("INNumeric_13_3_NTGEW", iNNumeric_13_3_NTGEW) :
                new ObjectParameter("INNumeric_13_3_NTGEW", typeof(decimal));
    
            var iNStringGEWEIParameter = iNStringGEWEI != null ?
                new ObjectParameter("INStringGEWEI", iNStringGEWEI) :
                new ObjectParameter("INStringGEWEI", typeof(string));
    
            var iNNumeric_13_3_VOLUMParameter = iNNumeric_13_3_VOLUM.HasValue ?
                new ObjectParameter("INNumeric_13_3_VOLUM", iNNumeric_13_3_VOLUM) :
                new ObjectParameter("INNumeric_13_3_VOLUM", typeof(decimal));
    
            var iNStringVOLEHParameter = iNStringVOLEH != null ?
                new ObjectParameter("INStringVOLEH", iNStringVOLEH) :
                new ObjectParameter("INStringVOLEH", typeof(string));
    
            var iNStringSTEUCParameter = iNStringSTEUC != null ?
                new ObjectParameter("INStringSTEUC", iNStringSTEUC) :
                new ObjectParameter("INStringSTEUC", typeof(string));
    
            var iNStringNALADISHParameter = iNStringNALADISH != null ?
                new ObjectParameter("INStringNALADISH", iNStringNALADISH) :
                new ObjectParameter("INStringNALADISH", typeof(string));
    
            var iNStringFABITMParameter = iNStringFABITM != null ?
                new ObjectParameter("INStringFABITM", iNStringFABITM) :
                new ObjectParameter("INStringFABITM", typeof(string));
    
            var iNStringATOCONParameter = iNStringATOCON != null ?
                new ObjectParameter("INStringATOCON", iNStringATOCON) :
                new ObjectParameter("INStringATOCON", typeof(string));
    
            var iNCharAMCCPTCParameter = iNCharAMCCPTC != null ?
                new ObjectParameter("INCharAMCCPTC", iNCharAMCCPTC) :
                new ObjectParameter("INCharAMCCPTC", typeof(string));
    
            var iNCharBRCCPTCParameter = iNCharBRCCPTC != null ?
                new ObjectParameter("INCharBRCCPTC", iNCharBRCCPTC) :
                new ObjectParameter("INCharBRCCPTC", typeof(string));
    
            var iNCharCCROMParameter = iNCharCCROM != null ?
                new ObjectParameter("INCharCCROM", iNCharCCROM) :
                new ObjectParameter("INCharCCROM", typeof(string));
    
            var iNStringFABRILUFParameter = iNStringFABRILUF != null ?
                new ObjectParameter("INStringFABRILUF", iNStringFABRILUF) :
                new ObjectParameter("INStringFABRILUF", typeof(string));
    
            var iNDecimal_11_2_NETPRORIParameter = iNDecimal_11_2_NETPRORI.HasValue ?
                new ObjectParameter("INDecimal_11_2_NETPRORI", iNDecimal_11_2_NETPRORI) :
                new ObjectParameter("INDecimal_11_2_NETPRORI", typeof(decimal));
    
            var iNDecimal_5_0_KPEINORIParameter = iNDecimal_5_0_KPEINORI.HasValue ?
                new ObjectParameter("INDecimal_5_0_KPEINORI", iNDecimal_5_0_KPEINORI) :
                new ObjectParameter("INDecimal_5_0_KPEINORI", typeof(decimal));
    
            var iNStringMEINSORIParameter = iNStringMEINSORI != null ?
                new ObjectParameter("INStringMEINSORI", iNStringMEINSORI) :
                new ObjectParameter("INStringMEINSORI", typeof(string));
    
            var iNDecimal_15_2_NETWRORIParameter = iNDecimal_15_2_NETWRORI.HasValue ?
                new ObjectParameter("INDecimal_15_2_NETWRORI", iNDecimal_15_2_NETWRORI) :
                new ObjectParameter("INDecimal_15_2_NETWRORI", typeof(decimal));
    
            var iNStringPRODParameter = iNStringPROD != null ?
                new ObjectParameter("INStringPROD", iNStringPROD) :
                new ObjectParameter("INStringPROD", typeof(string));
    
            var iNDateFKDATParameter = iNDateFKDAT.HasValue ?
                new ObjectParameter("INDateFKDAT", iNDateFKDAT) :
                new ObjectParameter("INDateFKDAT", typeof(System.DateTime));
    
            var iNStringTypeTGTESHPNParameter = iNStringTypeTGTESHPN != null ?
                new ObjectParameter("INStringTypeTGTESHPN", iNStringTypeTGTESHPN) :
                new ObjectParameter("INStringTypeTGTESHPN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSalvaTGTESHPN", iNIntIDEmbarqueParameter, iNIntSBELPParameter, iNIntNBELPParameter, iNStringDOCFATParameter, iNNumeric_13_3_ITMFATParameter, iNStringMATNRParameter, iNStringMAKTXParameter, iNNumeric_11_2_QTDITMParameter, iNDecimal_11_2_NETPRParameter, iNDecimal_5_0_KPEINParameter, iNStringMEINSParameter, iNDecimal_11_2_NETWRParameter, iNDecimal_15_2_FRTLOCParameter, iNDecimal_15_2_FRTINTParameter, iNDecimal_15_2_SEGINTParameter, iNDecimal_15_2_PRCFOBParameter, iNDecimal_15_2_PRCEXWParameter, iNDecimal_15_2_PCTCOMParameter, iNDecimal_15_2_VLRCOMParameter, iNStringRENUMParameter, iNIntITMREParameter, iNStringENQDMParameter, iNNumeric_13_3_BRGEWParameter, iNNumeric_13_3_NTGEWParameter, iNStringGEWEIParameter, iNNumeric_13_3_VOLUMParameter, iNStringVOLEHParameter, iNStringSTEUCParameter, iNStringNALADISHParameter, iNStringFABITMParameter, iNStringATOCONParameter, iNCharAMCCPTCParameter, iNCharBRCCPTCParameter, iNCharCCROMParameter, iNStringFABRILUFParameter, iNDecimal_11_2_NETPRORIParameter, iNDecimal_5_0_KPEINORIParameter, iNStringMEINSORIParameter, iNDecimal_15_2_NETWRORIParameter, iNStringPRODParameter, iNDateFKDATParameter, iNStringTypeTGTESHPNParameter, oUTId);
        }
    
        public virtual int spObtemIDEmbarque(string iNStringEmbarque, ObjectParameter oUTID)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spObtemIDEmbarque", iNStringEmbarqueParameter, oUTID);
        }
    
        public virtual int spSalvaMAKTX_TEXT(Nullable<int> iNIntIDTGTESHPN, string iNStringText, string iNStringType)
        {
            var iNIntIDTGTESHPNParameter = iNIntIDTGTESHPN.HasValue ?
                new ObjectParameter("INIntIDTGTESHPN", iNIntIDTGTESHPN) :
                new ObjectParameter("INIntIDTGTESHPN", typeof(int));
    
            var iNStringTextParameter = iNStringText != null ?
                new ObjectParameter("INStringText", iNStringText) :
                new ObjectParameter("INStringText", typeof(string));
    
            var iNStringTypeParameter = iNStringType != null ?
                new ObjectParameter("INStringType", iNStringType) :
                new ObjectParameter("INStringType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSalvaMAKTX_TEXT", iNIntIDTGTESHPNParameter, iNStringTextParameter, iNStringTypeParameter);
        }
    
        public virtual ObjectResult<string> spConsultaDetalheEmbarqueSalvo(Nullable<int> iNIntIdEmbarque)
        {
            var iNIntIdEmbarqueParameter = iNIntIdEmbarque.HasValue ?
                new ObjectParameter("INIntIdEmbarque", iNIntIdEmbarque) :
                new ObjectParameter("INIntIdEmbarque", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spConsultaDetalheEmbarqueSalvo", iNIntIdEmbarqueParameter);
        }
    
        public virtual int spExcluiDetalheEmbarque(Nullable<int> iNIntIdEmbarque)
        {
            var iNIntIdEmbarqueParameter = iNIntIdEmbarque.HasValue ?
                new ObjectParameter("INIntIdEmbarque", iNIntIdEmbarque) :
                new ObjectParameter("INIntIdEmbarque", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spExcluiDetalheEmbarque", iNIntIdEmbarqueParameter);
        }
    
        public virtual ObjectResult<spConsultaRequest_Result> spConsultaRequest(Nullable<byte> iNTinyintMensagem, Nullable<int> iNIntIDDadosBroker)
        {
            var iNTinyintMensagemParameter = iNTinyintMensagem.HasValue ?
                new ObjectParameter("INTinyintMensagem", iNTinyintMensagem) :
                new ObjectParameter("INTinyintMensagem", typeof(byte));
    
            var iNIntIDDadosBrokerParameter = iNIntIDDadosBroker.HasValue ?
                new ObjectParameter("INIntIDDadosBroker", iNIntIDDadosBroker) :
                new ObjectParameter("INIntIDDadosBroker", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaRequest_Result>("spConsultaRequest", iNTinyintMensagemParameter, iNIntIDDadosBrokerParameter);
        }
    
        public virtual int spAlterarDetalheEmbarqueAtualizado(Nullable<int> iNIntIdEmbarque)
        {
            var iNIntIdEmbarqueParameter = iNIntIdEmbarque.HasValue ?
                new ObjectParameter("INIntIdEmbarque", iNIntIdEmbarque) :
                new ObjectParameter("INIntIdEmbarque", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAlterarDetalheEmbarqueAtualizado", iNIntIdEmbarqueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spConsultaDetalheEmbarqueList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spConsultaDetalheEmbarqueList");
        }
    
        public virtual int spSalvaRetorno(string iNEmbarque, string iNStringCode, string iNStringDesc, Nullable<System.DateTime> iNDateTimeDataRetorno, Nullable<byte> iNTinyintMensagem, ObjectParameter oUTID)
        {
            var iNEmbarqueParameter = iNEmbarque != null ?
                new ObjectParameter("INEmbarque", iNEmbarque) :
                new ObjectParameter("INEmbarque", typeof(string));
    
            var iNStringCodeParameter = iNStringCode != null ?
                new ObjectParameter("INStringCode", iNStringCode) :
                new ObjectParameter("INStringCode", typeof(string));
    
            var iNStringDescParameter = iNStringDesc != null ?
                new ObjectParameter("INStringDesc", iNStringDesc) :
                new ObjectParameter("INStringDesc", typeof(string));
    
            var iNDateTimeDataRetornoParameter = iNDateTimeDataRetorno.HasValue ?
                new ObjectParameter("INDateTimeDataRetorno", iNDateTimeDataRetorno) :
                new ObjectParameter("INDateTimeDataRetorno", typeof(System.DateTime));
    
            var iNTinyintMensagemParameter = iNTinyintMensagem.HasValue ?
                new ObjectParameter("INTinyintMensagem", iNTinyintMensagem) :
                new ObjectParameter("INTinyintMensagem", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSalvaRetorno", iNEmbarqueParameter, iNStringCodeParameter, iNStringDescParameter, iNDateTimeDataRetornoParameter, iNTinyintMensagemParameter, oUTID);
        }
    
        public virtual ObjectResult<spConsultaDetalheEmbarqueMAKTX_TEXT_Result> spConsultaDetalheEmbarqueMAKTX_TEXT(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaDetalheEmbarqueMAKTX_TEXT_Result>("spConsultaDetalheEmbarqueMAKTX_TEXT", iNStringEmbarqueParameter);
        }
    
        public virtual ObjectResult<spConsultaDetalheEmbarqueSHPTEXT_Result> spConsultaDetalheEmbarqueSHPTEXT(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaDetalheEmbarqueSHPTEXT_Result>("spConsultaDetalheEmbarqueSHPTEXT", iNStringEmbarqueParameter);
        }
    
        public virtual ObjectResult<spConsultaDetalheEmbarqueTGTEPRD_Result> spConsultaDetalheEmbarqueTGTEPRD(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaDetalheEmbarqueTGTEPRD_Result>("spConsultaDetalheEmbarqueTGTEPRD", iNStringEmbarqueParameter);
        }
    
        public virtual ObjectResult<spConsultaDetalheEmbarqueTGTERES_Result> spConsultaDetalheEmbarqueTGTERES(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaDetalheEmbarqueTGTERES_Result>("spConsultaDetalheEmbarqueTGTERES", iNStringEmbarqueParameter);
        }
    
        public virtual ObjectResult<spConsultaDetalheEmbarqueTGTESHKN_Result> spConsultaDetalheEmbarqueTGTESHKN(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaDetalheEmbarqueTGTESHKN_Result>("spConsultaDetalheEmbarqueTGTESHKN", iNStringEmbarqueParameter);
        }
    
        public virtual ObjectResult<spConsultaDetalheEmbarqueTGTESHPN_Result> spConsultaDetalheEmbarqueTGTESHPN(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaDetalheEmbarqueTGTESHPN_Result>("spConsultaDetalheEmbarqueTGTESHPN", iNStringEmbarqueParameter);
        }
    
        public virtual ObjectResult<spConsultaEmbarquesAtualizarDetalhe_Result> spConsultaEmbarquesAtualizarDetalhe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaEmbarquesAtualizarDetalhe_Result>("spConsultaEmbarquesAtualizarDetalhe");
        }
    
        public virtual ObjectResult<spConsultaEmbarquePrestacaoConta_Result> spConsultaEmbarquePrestacaoConta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaEmbarquePrestacaoConta_Result>("spConsultaEmbarquePrestacaoConta");
        }
    
        public virtual int spAlterarEnviaPrestContaEmbarqueAtualizado(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAlterarEnviaPrestContaEmbarqueAtualizado", iNStringEmbarqueParameter);
        }
    
        public virtual ObjectResult<spConsultaPC_Result> spConsultaPC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaPC_Result>("spConsultaPC");
        }
    
        public virtual ObjectResult<spConsultaAtualizacaoPC_TPCK_Result> spConsultaAtualizacaoPC_TPCK(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaAtualizacaoPC_TPCK_Result>("spConsultaAtualizacaoPC_TPCK", iNStringEmbarqueParameter);
        }
    
        public virtual int spAlterarDetalheEmbarqueConsultado(string iNStringSBLN)
        {
            var iNStringSBLNParameter = iNStringSBLN != null ?
                new ObjectParameter("INStringSBLN", iNStringSBLN) :
                new ObjectParameter("INStringSBLN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAlterarDetalheEmbarqueConsultado", iNStringSBLNParameter);
        }
    
        public virtual int spAtualizaPrestacaoConta_TPCK(Nullable<int> iNIntIDEmbarque, string iNStringPCTYP, string iNStringDOCNR, string iNStringSTATU)
        {
            var iNIntIDEmbarqueParameter = iNIntIDEmbarque.HasValue ?
                new ObjectParameter("INIntIDEmbarque", iNIntIDEmbarque) :
                new ObjectParameter("INIntIDEmbarque", typeof(int));
    
            var iNStringPCTYPParameter = iNStringPCTYP != null ?
                new ObjectParameter("INStringPCTYP", iNStringPCTYP) :
                new ObjectParameter("INStringPCTYP", typeof(string));
    
            var iNStringDOCNRParameter = iNStringDOCNR != null ?
                new ObjectParameter("INStringDOCNR", iNStringDOCNR) :
                new ObjectParameter("INStringDOCNR", typeof(string));
    
            var iNStringSTATUParameter = iNStringSTATU != null ?
                new ObjectParameter("INStringSTATU", iNStringSTATU) :
                new ObjectParameter("INStringSTATU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAtualizaPrestacaoConta_TPCK", iNIntIDEmbarqueParameter, iNStringPCTYPParameter, iNStringDOCNRParameter, iNStringSTATUParameter);
        }
    
        public virtual int spAlterarConsultaPrestContaEmbarqueRealizado(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAlterarConsultaPrestContaEmbarqueRealizado", iNStringEmbarqueParameter);
        }
    
        public virtual int spAtualizaPrestacaoConta_TXPNS(Nullable<int> iNIntIDPCK, string iNStringKSCHL, Nullable<decimal> iNDecimalNETWR)
        {
            var iNIntIDPCKParameter = iNIntIDPCK.HasValue ?
                new ObjectParameter("INIntIDPCK", iNIntIDPCK) :
                new ObjectParameter("INIntIDPCK", typeof(int));
    
            var iNStringKSCHLParameter = iNStringKSCHL != null ?
                new ObjectParameter("INStringKSCHL", iNStringKSCHL) :
                new ObjectParameter("INStringKSCHL", typeof(string));
    
            var iNDecimalNETWRParameter = iNDecimalNETWR.HasValue ?
                new ObjectParameter("INDecimalNETWR", iNDecimalNETWR) :
                new ObjectParameter("INDecimalNETWR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAtualizaPrestacaoConta_TXPNS", iNIntIDPCKParameter, iNStringKSCHLParameter, iNDecimalNETWRParameter);
        }
    
        public virtual ObjectResult<spObtemIDPrestacaoConta_Result> spObtemIDPrestacaoConta(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtemIDPrestacaoConta_Result>("spObtemIDPrestacaoConta", iNStringEmbarqueParameter);
        }
    
        public virtual int spDetalheError(Nullable<int> iNIdStatusRetorno, string iNStringCode, string iNStringDesc)
        {
            var iNIdStatusRetornoParameter = iNIdStatusRetorno.HasValue ?
                new ObjectParameter("INIdStatusRetorno", iNIdStatusRetorno) :
                new ObjectParameter("INIdStatusRetorno", typeof(int));
    
            var iNStringCodeParameter = iNStringCode != null ?
                new ObjectParameter("INStringCode", iNStringCode) :
                new ObjectParameter("INStringCode", typeof(string));
    
            var iNStringDescParameter = iNStringDesc != null ?
                new ObjectParameter("INStringDesc", iNStringDesc) :
                new ObjectParameter("INStringDesc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDetalheError", iNIdStatusRetornoParameter, iNStringCodeParameter, iNStringDescParameter);
        }
    
        public virtual ObjectResult<spConsultaAtualizacaoPC_TXPNS_Result> spConsultaAtualizacaoPC_TXPNS(string iNStringEmbarque)
        {
            var iNStringEmbarqueParameter = iNStringEmbarque != null ?
                new ObjectParameter("INStringEmbarque", iNStringEmbarque) :
                new ObjectParameter("INStringEmbarque", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultaAtualizacaoPC_TXPNS_Result>("spConsultaAtualizacaoPC_TXPNS", iNStringEmbarqueParameter);
        }
    }
}
